### ISSUE TITLE
index.php在页面上显示奇怪的内容，似乎是报错的的信息

### ISSUE THREAD

**Issue by archibate** [RazeSoldier/science_tool#2]
为什么physics/index.php会报错说变量未命名？
D:/physics/index.php: undefined什么什么
（and。。光速是不会变的，不需要引入继承吧，直接在一个文件里实现就可以了，而你居然另外开了个域名）

**Comment by archibate** [comment]
不过你真的好厉害

**Comment by RazeSoldier** [comment]
> 为什么physics/index.php会报错说变量未命名？

我想这个问题已经解决了，估计是我后台把display_error打开了。

> 光速是不会变的，不需要引入继承吧，直接在一个文件里实现就可以了

我想代码重用，现在有很多文件里都涉及这个光速
